# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: yazidchen.github.io
date_format: "ordinal"
title: YazidChen Blog
subtitle: "路途甚远，早些起行"
description: "不归路，因兴趣而铺"
keywords: YazidChen, YazidChen Blog
favicon: /favicon.ico
timezone: Asia/ShenZhen
encoding: "utf-8"
source_code: https://github.com/YazidChen/yazidchen.github.io

# ---------------- #
#      Author      #
# ---------------- #
author: YazidChen
location: ShenZhen, China
email: chenzesheng1994@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: YazidChen

